### ISSUE TITLE
Raytracing Article

### ISSUE THREAD

**Issue by ghost** [LWJGL/lwjgl3-wiki#1]
Is raytracing article going to be finished? It is the most readable article on the internet and I'd like to try it out

**Comment by httpdigest** [comment]
Hi, and thanks for the kind words. :)
There are currently no plans to continue this article series. It's a whole lot of work. :)
But if you want to play with some demos that developed beyond the articles, have a look at: https://github.com/LWJGL/lwjgl3-demos/tree/master/src/org/lwjgl/demo/opengl/raytracing

**Comment by tlf30** [comment]
If part two is not going to be developed, references to it should be removed from the wiki.
