### ISSUE TITLE
lwjgl  3.2.4-snapshot not exists.

### ISSUE THREAD

**Issue by LightSun** [LWJGL/lwjgl3-wiki#10]

**Comment by httpdigest** [comment]
If by that you mean that you could not find that snapshot version in Maven Central, then: yes. Maven Central only hosts release versions of artifacts, not snapshot versions.
LWJGL 3 itself pushes snapshot versions to oss.sonatype.org.
Here is the repo URL: https://oss.sonatype.org/content/repositories/snapshots/
