### ISSUE TITLE
Broken link - Tutorials page

### ISSUE THREAD

**Issue by mokuhasushi** [LWJGL/lwjgl3-wiki#11]
Hi, 

I wanted to point out a broken link on the [tutorials page](https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.-Tutorial-Index): [LWJGL 3 Fundamentals](https://tutorialedge.net/course/lwjgl-3-fundamentals)

Antonio

**Comment by httpdigest** [comment]
Thanks, I deleted the reference to that tutorial as I also couldn't find any replacement. It seems that particular tutorial simply doesn't exist anymore online.
