### ISSUE TITLE
update samples to work with the latest version

### ISSUE THREAD

**Issue by goofyseeker311** [LWJGL/lwjgl3-wiki#12]
2.6.1. Ray tracing with OpenGL Compute Shaders (Part I), both demo01 and demo01_30 have multiple issues.
for example. not simple to fix for first lwjgl3 user, even case changes in class names, tried with version 3.2.3.

**Comment by httpdigest** [comment]
Thanks for pointing it out!
I'll port those demos to the https://github.com/LWJGL/lwjgl3-demos/tree/main/src/org/lwjgl/demo/opengl/raytracing repository to always work with the latest LWJGL version and link the GitHub repo in the Wiki article.
You'll find much more advanced demos/examples there.

**Comment by goofyseeker311** [comment]
It needs to be compute shaders, opencl, not specifically raytracing, even if used for ray tracing

**Comment by goofyseeker311** [comment]
Could you do a ray tracing using real time distance field update, sphere volume collision based, simple compute shader sample,
or just a simple basic compute shader sample, stub sample program

Could also be hierarchical kd-tree type sphere distance field demo

Ideas in comment cant be removed because they need to be stated in all publications not in public domain.
