### ISSUE TITLE
About the link to LWJGL2

### ISSUE THREAD

**Issue by heipiao233** [LWJGL/lwjgl3-wiki#14]
`LWJGL 3 is a fresh start and LWJGL 2 is its predecessor. LWJGL 2 has been used in the creation of dozens of games, including titles like [Minecraft](https://minecraft.net/) by Mojang and [Revenge of the Titans](http://www.puppygames.net/revenge-of-the-titans/) by Puppygames. It was also used in popular game engines, like [libGDX](https://libgdx.com/) and [jMonkeyEngine](http://jmonkeyengine.org/).`
Yes, but Minecraft is now using LWJGL3

**Comment by SWinxy** [comment]
The sentence is correct. Minecraft's creation was with LWJGL 2. They have since moved on to using LWJGL 3.

**Comment by heipiao233** [comment]
Sorry, my English is bad.
