### ISSUE TITLE
Source Code link Broken

### ISSUE THREAD

**Issue by User-HC-Git** [LWJGL/lwjgl3-wiki#2]
The links to the accompanying code are broken.

**Comment by SilverTiger** [comment]
What links are you talking about?
Could you post the articles with the broken links?

**Comment by codedcosmos** [comment]
On the page 2.6.1 Ray tracing with OpenGL Compute Shaders (Part I)

https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.1.-Ray-tracing-with-OpenGL-Compute-Shaders-%28Part-I%29

At the bottom of the page the link:
http://d2g0ezo1t7nqa0.cloudfront.net/tutorials/141208_glsl_compute/rt_glsl_compute_pt1.zip

Is currently not working

**Comment by seventh-chord** [comment]
Tagging @httpdigest, I think he originally wrote this article. Maybe he still has the code locally :)

**Comment by httpdigest** [comment]
The link to the code example zip file has been fixed now. Thanks for reporting!
Please note that the code is from December of 2014, so somewhat two years before the first release of LWJGL 3. It will therefore not work with any currently downloadable version of LWJGL 3 anymore, so requires some small modifications to make it work.

Please have a look at the [lwjgl3-demos](https://github.com/LWJGL/lwjgl3-demos/tree/master/src/org/lwjgl/demo/opengl/raytracing) repository. It contains up-to-date code examples including many different variations of the original pathtracing example.
