### ISSUE TITLE
Small issue with openal example/tutorial

### ISSUE THREAD

**Issue by codedcosmos** [LWJGL/lwjgl3-wiki#5]
The import used for the code is
`import static org.lwjgl.system.libc.Stdlib.free;`

Which is nolonger included in lwjgl, at least in 3.16.
The import line should be replaced with:
`import static org.lwjgl.system.libc.LibCStdlib.*;`

This issue comes from:
https://github.com/LWJGL/lwjgl3-wiki/wiki/2.1.-OpenAL

Disclaimer:
Im new to github, and kind of a noob, if I should have sent this issue request elsewhere or I need to do something else, let me know.

**Comment by Spasi** [comment]
Fixed with [revision 6](https://github.com/LWJGL/lwjgl3-wiki/wiki/2.1.-OpenAL/f323b68df7552ded8dc33051937b57b9b97aba69).

Reporting wiki issues this way is perfect, thanks!
