### ISSUE TITLE
Syntax Error in Input Handling Tutorial

### ISSUE THREAD

**Issue by jontyrudman** [LWJGL/lwjgl3-wiki#8]
There seems to be an extra close bracket after `GLFWKeyCallback()`:

```
glfwSetKeyCallback(window, keyCallback = new GLFWKeyCallback()){
    @Override
    public void invoke (long window, int key, int scancode, int action, int mods) {

    }
});
```

This caused me a headache for a good half an hour, so I thought I'd bring it up.

[Here's the page on the wiki](https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.3-Input-handling-with-GLFW)

**Comment by SilverTiger** [comment]
Thanks! Fixed with [cc2c58a](https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.3-Input-handling-with-GLFW/cc2c58aef3c85ca05ac57fc5f333eefbb4f2cbeb).
