### ISSUE TITLE
wanted to ask about continuation

### ISSUE THREAD

**Issue by SidsiRocks** [LWJGL/lwjgl3-wiki#9]
This was an awesome article but there hasn't been a new article in some time correct me if i am wrong and cannot find it(new to github).

**Comment by httpdigest** [comment]
It's unclear what you are talking about. lwjgl3-wiki houses multiple articles/posts (see the index/navigation to the right on here https://github.com/LWJGL/lwjgl3-wiki/wiki ).
If you could add a reference to the article you have found, then its author can probably answer.

**Comment by SidsiRocks** [comment]
Sorry my mistake i just came here from the link for the ray Casting tutorial i will make the question more clear and repost it

**Comment by httpdigest** [comment]
Alright, I just closed it since for three days you did not respond. No need to repost. There has been two other questions/issues in the past about it. Look in the closed GitHub issues here:
https://github.com/LWJGL/lwjgl3-wiki/issues/1
https://github.com/LWJGL/lwjgl3-wiki/issues/4

**Comment by SidsiRocks** [comment]
Sorry hadn't seen those already reposted will withdraw it soon
